services:
  api:
    build: .
    container_name: competition-analyser-api
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GCP_CREDENTIALS_PATH=${GCP_CREDENTIALS_PATH}
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.evaluator.rule=Host(`evaluator.hidevs.xyz`)"
      - "traefik.http.routers.evaluator.entrypoints=websecure"
      - "traefik.http.routers.evaluator.tls=true"
      - "traefik.http.routers.evaluator.tls.certresolver=mytlschallenge"
      - "traefik.http.services.evaluator.loadbalancer.server.port=8000"
    networks:
      - competition-net
      - traefik-net

networks:
  competition-net:
  traefik-net:
    external: true
